name: Paintor
main: net.nightpool.bukkit.paintor.PaintPlugin
version: maven-version-number
commands:
   paintor: 
      description: This is the main command. Toggles painting mode, or toggles a specific foundational block. 
      usage: /<command> [on|off|materials...]
      aliases: [paint, pn]